service: ${self:custom.deployConfig.projectName}
frameworkVersion: "3"

package:
  exclude:
    - api/venv/**
    - api/__pycache__/*
    - client/**
    - node_modules/**
    - README.md
    - package.json
    - package-lock.json

plugins:
  - serverless-localstack
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-s3-deploy

custom:
  deployConfig:
    projectName: ${file(deploy-config.json):projectName}
    timeout: ${file(deploy-config.json):timeout}
    memorySize: ${file(deploy-config.json):memorySize}
    stages:
      local:
        region: ${file(deploy-config.json):stages.local.region}
        includeLayers: false
        layer: AWS::NoValue
        requirements: local-requirements.txt
      prd:
        region: ${file(deploy-config.json):stages.prd.region}
        includeLayers: true
        layer: PythonRequirementsLambdaLayer
        requirements: prd-requirements.txt
      stg:
        region: ${file(deploy-config.json):stages.stg.region}
        includeLayers: true
        layer: PythonRequirementsLambdaLayer
        requirements: stg-requirements.txt

  buckets:
    staticFiles:
      name: static-files-${opt:stage, 'local'}
      region: sa-east-1
    dist:
      name: dist-${opt:stage, 'local'}
      region: sa-east-1

  assets:
    auto: false
    targets:
      - bucket:
          Ref: DistBucket
        acl: public-read
        files:
          - source: client/dist/${opt:stage, 'local'}/
            headers:
              CacheControl: max-age=31104000 # 1 year
            globs:
              - "**/*"
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    edgePort: 4566 # optional - LocalStack edge port to connect to

  wsgi:
    app: api.config.wsgi.application

  pythonRequirements:
    fileName: ./api/config/requirements/compiled/${self:custom.deployConfig.stages.${opt:stage, 'local'}.requirements}
    layer: ${self:custom.deployConfig.stages.${opt:stage, 'local'}.includeLayers}

provider:
  name: aws
  timeout: ${self:custom.deployConfig.timeout}
  memorySize: ${self:custom.deployConfig.memorySize}
  runtime: python3.11
  stage: ${opt:stage, 'local'}
  region: ${self:custom.deployConfig.stages.${opt:stage, 'local'}.region}
  environment:
    STATIC_FILES_BUCKET_NAME: ${self:custom.buckets.staticFiles.name}
    STATIC_FILES_BUCKET_REGION: ${self:custom.buckets.staticFiles.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::${self:custom.buckets.staticFiles.name}
            - arn:aws:s3:::${self:custom.buckets.staticFiles.name}/*

        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:PutParameter
          Resource: "arn:aws:ssm:*:*:*"

functions: ${file(serverless.functions.yml):functions}

resources: ${file(serverless.resources.yml):resources}
