service: django-sls
frameworkVersion: '3'
useDotenv: true

package:
  exclude:
    - api/venv/**
    - api/__pycache__/*
    - api/node_modules/**
    - README.md
    - api/package.json
    - api/package-lock.json
	
plugins:
  - serverless-localstack
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    edgePort: 4566  # optional - LocalStack edge port to connect to

  wsgi:
    app: api.config.wsgi.application

  pythonRequirements:
    fileName: ./api/requirements.txt

provider:
  name: aws
  runtime: python3.11
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::${env:STATIC_FILES_BUCKET_NAME}
            - arn:aws:s3:::${env:STATIC_FILES_BUCKET_NAME}/*

functions:
  api:
    handler: wsgi_handler.handler
    events:
    - http:
        path: /
        method: ANY
    - http:
        path: /{proxy+}
        method: ANY

resources:
  Resources:
    StaticFilesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:STATIC_FILES_BUCKET_NAME}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    StaticFilesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticFilesBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Action: "s3:GetObject"
              Effect: Allow
              Principal: "*"
              Resource: "arn:aws:s3:::${env:STATIC_FILES_BUCKET_NAME}/*"
