version: "3.8"

services:
  local_setup:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: local_setup
    depends_on:
      - localstack
    networks:
      - bridge_network
    command: [python, ./app/load_variables.py]


  localstack:
    container_name: localstack
    image: localstack/localstack:3.5.0-amd64
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test_id
      - AWS_SECRET_ACCESS_KEY=test_secret
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - bridge_network

  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: api
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
    depends_on:
      - postgres_db
      - local_setup
    volumes:
      - ../api:/usr/src
    ports:
      - "8000:8000"
      - "6000:6000"
    networks:
      - bridge_network

  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/ 
    networks:
      - bridge_network

networks: 
  bridge_network:
    driver: bridge

volumes:
  postgres_volume: